"""Add social media fields

Revision ID: 15107c45ecb4
Revises: 4c7fc99d143c
Create Date: 2020-08-23 11:17:08.156127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15107c45ecb4'
down_revision = '4c7fc99d143c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('societies', sa.Column('social_1', sa.String(), nullable=True))
    op.add_column('societies', sa.Column('social_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('societies', 'social_2')
    op.drop_column('societies', 'social_1')
    # ### end Alembic commands ###
