"""Add session JSON field

Revision ID: 1570277296f2
Revises: 15107c45ecb4
Create Date: 2020-08-23 13:54:36.481484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1570277296f2'
down_revision = '15107c45ecb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('societies', sa.Column('sessions', sa.JSON(), nullable=False, server_default="[]"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('societies', 'sessions')
    # ### end Alembic commands ###
