"""Add password field to rooms

Revision ID: 23826c2f7783
Revises: 7e6ece2e01a5
Create Date: 2020-09-30 09:05:49.824832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23826c2f7783'
down_revision = '7e6ece2e01a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'password')
    # ### end Alembic commands ###
