"""Add social fields

Revision ID: 2c423286568f
Revises: 1570277296f2
Create Date: 2020-09-16 12:45:33.692464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c423286568f'
down_revision = '1570277296f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('societies', sa.Column('socials', sa.JSON(), nullable=False, server_default="[]"))
    op.alter_column('societies', 'sessions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('societies', 'social_2')
    op.drop_column('societies', 'social_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('societies', sa.Column('social_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('societies', sa.Column('social_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('societies', 'sessions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('societies', 'socials')
    # ### end Alembic commands ###
