"""Move from admins to owners

Revision ID: 35bae01be210
Revises: eb6dec54082a
Create Date: 2020-09-26 19:51:17.180591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35bae01be210'
down_revision = 'eb6dec54082a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # we need to drop constraints before renaming
    op.drop_constraint('user_society_admin_id_fkey', 'user_society', type_='foreignkey')
    op.alter_column('user_society', 'admin_id', new_column_name='user_id')
    op.create_foreign_key(None, 'user_society', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_society', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_society', type_='foreignkey')
    op.create_foreign_key('user_society_admin_id_fkey', 'user_society', 'users', ['admin_id'], ['id'])
    op.drop_column('user_society', 'owner_id')
    op.drop_table('settings')
    # ### end Alembic commands ###
