"""empty message

Revision ID: 42c343872516
Revises: 6acc09e8039c
Create Date: 2020-10-07 08:53:15.546502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c343872516'
down_revision = '6acc09e8039c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whitelist', 'room_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=28),
               existing_nullable=True)
    op.alter_column('whitelist', 'group_id',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users_groups', 'group_id',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20))
    op.alter_column('sessions', 'room_id',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=28),
               existing_nullable=True)
    op.alter_column('rooms', 'id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=28))
    op.alter_column('links', 'room_id',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=28),
               existing_nullable=True)
    op.alter_column('links', 'group_id',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('groups', 'id',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12))
    op.alter_column('links', 'group_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('links', 'room_id',
               existing_type=sa.VARCHAR(length=28),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('rooms', 'id',
               existing_type=sa.VARCHAR(length=28),
               type_=sa.String(length=20))
    op.alter_column('sessions', 'room_id',
               existing_type=sa.VARCHAR(length=28),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('users_groups', 'group_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12))
    op.alter_column('whitelist', 'group_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12),
               existing_nullable=True)
    op.alter_column('whitelist', 'room_id',
               existing_type=sa.VARCHAR(length=28),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
