"""Add short_description field

Revision ID: 57ea5a7749e1
Revises: 1570277296f2
Create Date: 2020-09-15 20:39:31.741043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57ea5a7749e1'
down_revision = '1570277296f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('societies', sa.Column('short_description', sa.String(length=200), nullable=True))
    op.alter_column('societies', 'sessions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('societies', 'sessions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('societies', 'short_description')
    # ### end Alembic commands ###
