"""Add first_name field

Revision ID: 66b34c4ccba0
Revises: 025a539edc8b
Create Date: 2020-08-18 11:51:34.299042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b34c4ccba0'
down_revision = '025a539edc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('surname', sa.String(), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'surname')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
