"""Add description field to rooms

Revision ID: 7512c137baa3
Revises: cb6e01963d11
Create Date: 2020-09-30 14:14:57.631767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7512c137baa3'
down_revision = 'cb6e01963d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###
