"""Remove first_name and surname fields

Revision ID: 7e6ece2e01a5
Revises: 48e75b77cac1
Create Date: 2020-09-29 21:05:26.572258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6ece2e01a5'
down_revision = '48e75b77cac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
