"""Add alias for room URLs

Revision ID: f88b5b38e917
Revises: 75413009a1d7
Create Date: 2020-09-29 08:58:12.390742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88b5b38e917'
down_revision = '75413009a1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('alias', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'rooms', ['alias'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'alias')
    # ### end Alembic commands ###
